"""Measure rigid handle/payload hit boxes from the reviewed GLB skin weights."""
import json
import struct
from pathlib import Path
import numpy as np

ROOT = Path(__file__).resolve().parents[2] / 'weapon-models' / 'assets'
FOLDERS = ['02-nunchucks', '04-kusarigama', '25-wrecking-ball']


def measure(folder):
    blob = (ROOT / folder / 'Model.glb').read_bytes()
    length = struct.unpack_from('<I', blob, 12)[0]
    data = json.loads(blob[20:20 + length])
    binary = blob[28 + length:]

    def accessor(index):
        a = data['accessors'][index]
        view = data['bufferViews'][a['bufferView']]
        dtype = np.dtype({5126: '<f4', 5123: '<u2', 5121: 'u1'}[a['componentType']])
        width = {'VEC3': 3, 'VEC4': 4}[a['type']]
        assert 'sparse' not in a
        return np.ndarray((a['count'], width), dtype=dtype, buffer=binary,
                          offset=view.get('byteOffset', 0) + a.get('byteOffset', 0),
                          strides=(view.get('byteStride', width * dtype.itemsize), dtype.itemsize))

    groups = {}

    def visit(index, parent):
        node = data['nodes'][index]
        if 'matrix' in node:
            local = np.array(node['matrix']).reshape(4, 4).T
        else:
            x, y, z, w = node.get('rotation', [0, 0, 0, 1])
            local = np.eye(4)
            local[:3, :3] = np.array([
                [1-2*(y*y+z*z), 2*(x*y-z*w), 2*(x*z+y*w)],
                [2*(x*y+z*w), 1-2*(x*x+z*z), 2*(y*z-x*w)],
                [2*(x*z-y*w), 2*(y*z+x*w), 1-2*(x*x+y*y)]]) @ np.diag(node.get('scale', [1, 1, 1]))
            local[:3, 3] = node.get('translation', [0, 0, 0])
        world = parent @ local
        if 'mesh' in node:
            names = [data['nodes'][j]['name'] for j in data['skins'][node['skin']]['joints']]
            for primitive in data['meshes'][node['mesh']]['primitives']:
                attrs = primitive['attributes']
                xyz = accessor(attrs['POSITION']) @ world[:3, :3].T + world[:3, 3]
                xyz *= [-1, 1, -1]  # Same GLB -> Studio axes as the imported templates.
                weights = accessor(attrs['WEIGHTS_0'])
                joints = accessor(attrs['JOINTS_0'])
                assert np.allclose(weights.max(axis=1), 1) and np.allclose(weights.sum(axis=1), 1)
                owner = joints[np.arange(len(joints)), weights.argmax(axis=1)]
                for j, name in enumerate(names):
                    groups.setdefault(name, []).append(xyz[owner == j])
        for child in node.get('children', []):
            visit(child, world)

    for index in data['scenes'][data.get('scene', 0)]['nodes']:
        visit(index, np.eye(4))
    groups = {name: np.concatenate(parts) for name, parts in groups.items()}
    points = np.concatenate(list(groups.values()))
    lo, hi = points.min(axis=0), points.max(axis=0)
    center, scale = (lo + hi) / 2, np.linalg.norm(hi - lo)
    result = {'proportions': ((hi - lo) / scale).tolist(), 'boxes': {}}
    for name, points in groups.items():
        if name != 'Handle_ROOT' and not name.endswith('_END'):
            continue
        lo, hi = points.min(axis=0), points.max(axis=0)
        result['boxes'][name] = {'center': (((lo + hi) / 2 - center) / scale).tolist(),
                                 'size': ((hi - lo) / scale).tolist()}
    return result


if __name__ == '__main__':
    result = {folder[:2]: measure(folder) for folder in FOLDERS}
    def vector(values):
        return 'Vector3.new(' + ','.join(f'{v:.10f}' for v in values) + ')'
    lines = ['-- Generated by measure_chain_geometry.py from unchanged reviewed GLB skins.', 'return {']
    for key, entry in result.items():
        lines.append(f" ['{key}']={{proportions={vector(entry['proportions'])},boxes={{")
        for name, box in entry['boxes'].items():
            lines.append(f"  ['{name}']={{center={vector(box['center'])},size={vector(box['size'])}}},")
        lines.append(' }},')
    lines.append('}')
    Path(__file__).with_name('ChainWeaponGeometry.luau').write_text('\n'.join(lines) + '\n', encoding='utf-8')
    print(json.dumps(result, indent=2))
