"""Turn arena-layout.json into a Studio placement script.

    python emit_studio_script.py

Writes BuildBeachCove.server.luau with the layout inlined, so the only thing it
needs in Studio is a folder of the 25 imported MeshParts.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent
layout = json.loads((ROOT / "arena-layout.json").read_text())

# Props that should never block a character or a projectile.
NON_COLLIDING_PREFIX = ("16-", "17-", "18-", "22-", "23-", "24-", "25-", "19-", "20-")


def lua_name(stem):
    """01-headland-short -> 01_Headland_Short, matching the generator's object names."""
    return "_".join(p.capitalize() if not p.isdigit() else p for p in stem.split("-"))


lines = []
lines.append('--!strict')
lines.append('-- Beach Cove arena assembly. Generated by emit_studio_script.py; edit that,')
lines.append('-- not this file.')
lines.append('--')
lines.append('-- Setup:')
lines.append('--   1. Import the 25 FBX files from exports/fbx at scale 1.0.')
lines.append('--   2. Put the resulting MeshParts in ServerStorage.BeachCoveKit, named as')
lines.append('--      below (01_Headland_Short, 02_Headland_Medium, ...).')
lines.append('--   3. Run this once. It builds Workspace.BeachCoveArena and is idempotent:')
lines.append('--      an existing arena is removed first.')
lines.append('--')
lines.append(f'-- Clear floor: {layout["arena_clear_diameter_studs"]:.0f} studs across, inside wall to inside wall.')
lines.append('--')
lines.append('-- Cliffs are scenery. Collision comes from the invisible BoundaryWall ring, as')
lines.append('-- MODULAR_CLIFF_KIT.md asks, because the visual meshes contain overlapping and')
lines.append('-- disconnected shells that make poor colliders.')
lines.append('')
lines.append('local ServerStorage = game:GetService("ServerStorage")')
lines.append('local Workspace = game:GetService("Workspace")')
lines.append('')
lines.append('local KIT = ServerStorage:FindFirstChild("BeachCoveKit")')
lines.append('assert(KIT, "ServerStorage.BeachCoveKit is missing - import the kit first")')
lines.append('')
lines.append(f'local ARENA_RADIUS = {layout["arena_clear_diameter_studs"] / 2}')
lines.append('local GROUND_Y = 0 -- raise this to sit the arena on an existing floor')
lines.append('')

# pivot offsets
lines.append('-- Roblox pivots a MeshPart at its bounding-box centre, not at the origin the')
lines.append('-- mesh was authored around, so each asset carries the offset from its ground')
lines.append('-- origin to that centre. It is applied after the yaw, not before.')
lines.append('local PIVOT: { [string]: Vector3 } = {')
for stem, info in sorted(layout["assets"].items()):
    x, y, z = info["pivot_offset"]
    # Bracket-quoted: these names start with a digit, so they are not valid Lua
    # identifiers and cannot be written as bare table keys.
    lines.append(f'\t["{lua_name(stem)}"] = Vector3.new({x}, {y}, {z}),')
lines.append('}')
lines.append('')

lines.append('-- {assetName, x, y, z, yawDegrees}')
lines.append('local INSTANCES = {')
for inst in layout["instances"]:
    px, py, pz = inst["position"]
    lines.append(f'\t{{"{lua_name(inst["asset"])}", {px}, {py}, {pz}, {inst["yaw_deg"]}}},')
lines.append('}')
lines.append('')

lines.append('local NON_COLLIDING: { [string]: boolean } = {')
for stem in sorted(layout["assets"]):
    if stem.startswith(NON_COLLIDING_PREFIX):
        lines.append(f'\t["{lua_name(stem)}"] = true,')
lines.append('}')
lines.append('')

lines.append('''local existing = Workspace:FindFirstChild("BeachCoveArena")
if existing then
	existing:Destroy()
end

local arena = Instance.new("Folder")
arena.Name = "BeachCoveArena"

local scenery = Instance.new("Folder")
scenery.Name = "Scenery"
scenery.Parent = arena

local missing: { [string]: boolean } = {}
local placed = 0

for _, entry in INSTANCES do
	local name, x, y, z, yaw = entry[1], entry[2], entry[3], entry[4], entry[5]
	local template = KIT:FindFirstChild(name)
	if not template then
		missing[name] = true
		continue
	end

	local part = template:Clone()
	part.Anchored = true
	part.CanCollide = not NON_COLLIDING[name]
	part.CanQuery = part.CanCollide
	part.CanTouch = false
	part.CastShadow = true
	-- Decorative meshes do not need precise collision geometry.
	if part:IsA("MeshPart") then
		part.CollisionFidelity = Enum.CollisionFidelity.Box
		part.RenderFidelity = Enum.RenderFidelity.Automatic
	end

	local base = CFrame.new(x, y + GROUND_Y, z) * CFrame.Angles(0, math.rad(yaw), 0)
	part.CFrame = base * CFrame.new(PIVOT[name] or Vector3.zero)
	part.Parent = scenery
	placed += 1
end

-- Invisible boundary: a ring of thin walls on the clear-floor circle. Characters
-- and enemies collide with this, never with the cliff meshes.
local boundary = Instance.new("Folder")
boundary.Name = "BoundaryWall"
boundary.Parent = arena

local SEGMENTS = 32
local segmentWidth = 2 * math.pi * ARENA_RADIUS / SEGMENTS * 1.08
for i = 1, SEGMENTS do
	local theta = (i - 1) / SEGMENTS * 2 * math.pi
	local wall = Instance.new("Part")
	wall.Name = string.format("Wall%02d", i)
	wall.Size = Vector3.new(segmentWidth, 60, 2)
	wall.Anchored = true
	wall.CanCollide = true
	wall.Transparency = 1
	wall.CastShadow = false
	wall.CFrame = CFrame.new(
		math.cos(theta) * ARENA_RADIUS,
		GROUND_Y + 30,
		math.sin(theta) * ARENA_RADIUS
	) * CFrame.Angles(0, -theta, 0)
	wall.Parent = boundary
end

arena.Parent = Workspace

local missingList = {}
for name in missing do
	table.insert(missingList, name)
end
if #missingList > 0 then
	table.sort(missingList)
	warn(("BeachCove: %d instances skipped, missing from the kit folder: %s")
		:format(#INSTANCES - placed, table.concat(missingList, ", ")))
end
print(("BeachCove: placed %d/%d instances, %d boundary segments, %.0f stud clear floor")
	:format(placed, #INSTANCES, SEGMENTS, ARENA_RADIUS * 2))
''')

out = ROOT / "BuildBeachCove.server.luau"
out.write_text("\n".join(lines) + "\n", encoding="utf-8")
print("wrote", out, f"({len(layout['instances'])} instances)")
